# Generated by Django 4.2.11 on 2024-07-07 17:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+234XXXXXXXXXX', or '234XXXXXXXXXX', or '0XXXXXXXXXX' .", regex='((^\\+234){1}\\d{10})|((^234)\\d{10})|((^0)(7|8|9){1}(0|1){1}[0–9]{8})')]),
        ),
    ]
